name: 'Exact Dependency Checker'
description: 'Validates whether a project uses version-specific dependencies only'
branding:
  color: "green"
  icon: "check-circle"
inputs:
  ignoredDepList:
    description: 'A list of names of dependencies ignored by the validation.'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'



