name: 'Exact Dependency Checker'
description: 'Validates whether a project uses version-specific dependencies only'
author: 'Matheus Jardim Bernardes'

branding:
  color: "green"
  icon: "check-circle"

inputs:
  packageJsonPath:
    description: 'Complete path of the package.json file to be evaluated'
    required: false
    default: 'package.json'

runs:
  using: 'node16'
  main: 'dist/index.js'
