##
# Tests the action on its own package.json
##

name: Test the action itself

on:
  pull_request:
  push:
    branches:
      - main
      - feature/**

jobs:
  self_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0

      - uses: actions/setup-node@v3.8.1
        with:
          node-version-file: '.nvmrc'

      - run: |
          npm ci
          npm run all
      - uses: ./
