name: Test the action itself
on:
  pull_request:
  push:
    branches:
      - main
      - feature/**

jobs:
  self_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2

      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 16

      - run: npm ci
      - uses: ./
        with:
          ignoredDepList: |
            dep1
            dep2
