##
# Runs tests and generate project's code coverage badge
# Coverage job was heavily inspired by https://nedbatchelder.com/blog/202209/making_a_coverage_badge.html
##

name: 'Jest'

on:
  pull_request:


jobs:
  test:
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
        node: [ 16, 18, 20 ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3.6.0

      - uses: actions/setup-node@v3.7.0
        with:
          node-version: ${{ matrix.node }}

      - run: npm ci
      - run: npx jest --coverageReporters="json" --collectCoverage=true
