##
# Runs tests and generate project's code coverage badge
# Coverage job was heavily inspired by https://nedbatchelder.com/blog/202209/making_a_coverage_badge.html
##

name: 'Coverage'

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: actions/setup-node@v4.0.1
        with:
          node-version-file: '.nvmrc'

      - run: npm ci
      - run: npx jest --coverageReporters="json" --collectCoverage=true

      - name: "Extract coverage percentage"
        run: |
          export TOTAL=$(npx jest --coverageReporters="text-summary" --collectCoverage=true | grep Statements | awk '{print $3}')
          export TOTAL="${TOTAL:: -1}"
          echo "total=$TOTAL" >> $GITHUB_ENV
          echo "### Total coverage: ${TOTAL}%" >> $GITHUB_STEP_SUMMARY

      - name: "Upload progress to gist, to update badge"
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          # GIST_TOKEN is a GitHub personal access token with scope "gist".
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: f17f5787f5b4ac05a4b5a5b73a32e446
          filename: test.json
          label: Coverage
          message: ${{ env.total }}%
          minColorRange: 50
          maxColorRange: 90
          valColorRange: ${{ env.total }}
